apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: zeus-dep
  name: zeus-dep
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: zeus-dep
  type: LoadBalancer