# Deployment file for python-app
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zeus-dep
    env: dev
  name: portfolio
spec:
  replicas: 2
  progressDeadlineSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: zeus-dep
      env: dev
  template:
    metadata:
      labels:
        app: zeus-dep
        env: dev
    spec:
      containers:
      - image: singharunk/portfolio:latest
        name: portfolio
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /index.html
            port: 5000